name: syncNewFunds

on:
  schedule:
    - cron: "30 19 * * 6" # Run every Sunday at 1:00 AM IST
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-new-funds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Sync new funds
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          EXIT_LOAD_API: ${{ secrets.EXIT_LOAD_API }}
          FULL_FUND_DATA_API: ${{ secrets.FULL_FUND_DATA_API }}
          SEARCH_API: ${{ secrets.SEARCH_API }}
        run: npm run syncnewfunds
