name: Update Mutual Fund NAV and Returns

on:
  schedule:
    - cron: "30 18 * * *" # 12:00 AM IST
    - cron: "30 19 * * *" # 1:00 AM IST
    - cron: "30 20 * * *" # 2:00 AM IST
    - cron: "30 21 * * *" # 3:00 AM IST
    - cron: "30 22 * * *" # 4:00 AM IST
    - cron: "30 1 * * *" # 7:00 AM IST
    - cron: "30 4 * * *" # 10:00 AM IST
    - cron: "30 6 * * *" # 12:00 PM IST
    - cron: "30 9 * * *" # 3:00 PM IST
    - cron: "30 12 * * *" # 6:00 PM IST
  workflow_dispatch:

jobs:
  update-nav-and-returns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Update NAV and returns
        id: update-script
        run: npm run update
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
