name: Weekly Updater

on:
  schedule:
    - cron: "00 23 * * 6" # Run every Sunday at 4:30 AM IST
  workflow_dispatch: # Allow manual trigger

jobs:
  weekly-updater:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Weekly Updater
        id: update-script
        run: npm run weeklyupdater
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FULL_FUND_DATA_API: ${{ secrets.FULL_FUND_DATA_API }}
